@startuml

title __CLASS's Class Diagram__\n

  namespace project {
    namespace Class {
      class project.Class.Cennik {
          + DataZmiany : String
          + Gabaryt : String
          + ID : int
          + Kwota : float
          + Limit : int
          + Opis : String
          + Cennik()
          + Cennik()
          + DodajCennik()
          + UsunCennik()
          + ZmienCennik()
          {static} + fillPriceList()
          + getDataZmiany()
          + getGabaryt()
          + getID()
          + getKwota()
          + getLimit()
          + getOpis()
          + setDataZmiany()
          + setGabaryt()
          + setID()
          + setKwota()
          + setLimit()
          + setOpis()
      }
    }
  }
  

  namespace project {
    namespace Class {
      class project.Class.Doplata {
          + ID : int
          + KwotaD : Float
          + TypDoplaty : String
          + Doplata()
          {static} + fillTableAdditional()
          + getKwotaD()
          + getTypDoplaty()
          + setKwotaD()
          + setTypDoplaty()
      }
    }
  }
  

  namespace project {
    namespace Class {
      class project.Class.Klient {
          + TypKlienta : boolean
          {static} + stage : Stage
          + Klient()
          + ZlozZamowienie()
      }
    }
  }
  

  namespace project {
    namespace Class {
      class project.Class.Kurier {
          + id : int
          + ilosc : int
          + imie : String
          + location : String
          {static} + stage : Stage
          + DodajKuriera()
          + Kurier()
          + Kurier()
          + Kurier()
          + UsunKuriera()
          + ZmienTyp()
          + getId()
          + getIlosc()
          + getImie()
          + getLocation()
          + getTypKuriera()
          + setId()
          + setIlosc()
          + setImie()
          + setLocation()
          + setTypKuriera()
          + start()
      }
    }
  }
  

  namespace project {
    namespace Class {
      class project.Class.Oddzial {
          + id : int
          + miejscowosc : String
          + Oddzial()
          {static} + addAction()
          {static} + fill_table()
          + getId()
          + getMiejscowosc()
          + setId()
          + setMiejscowosc()
      }
    }
  }
  

  namespace project {
    namespace Class {
      class project.Class.Oplata {
          + ID : int
          + Kwota : float
          + Status : boolean
          + Termin : String
          + DodajOplate()
          + Oplata()
          + SprawdzOplate()
          + WyliczOplate()
      }
    }
  }
  

  namespace project {
    namespace Class {
      class project.Class.Paczka {
          + ID : int
          + Waga : float
          + Wymiar : String
          + DodajPaczke()
          + Paczka()
          + ZmienDanePaczki()
      }
    }
  }
  

  namespace project {
    namespace Class {
      class project.Class.Spedytor {
          {static} + stage : Stage
          + PrzydzielKuriera()
          + Spedytor()
      }
    }
  }
  

  namespace project {
    namespace Class {
      enum SposobPlatnosci {
        Blik
        Gotowka
        Karta
        Przelew
      }
    }
  }
  

  namespace project {
    namespace Class {
      enum TypKuriera {
        koncowy
        poczatkowy
        pomiedzyOddzialami
      }
    }
  }
  

  namespace project {
    namespace Class {
      class project.Class.Uzytkownik {
          + ID : int
          {static} + stage : Stage
          - Haslo : String
          - Imie : String
          - Mail : String
          - Nazwisko : String
          - Telefon : int
          + Rejestracja()
          + Uzytkownik()
          + Wyloguj()
          + Zaloguj()
      }
    }
  }
  

  namespace project {
    namespace Class {
      class project.Class.Zlecenie {
          + AdresKoncowy : String
          + AdresPoczatkowy : String
          + DataNadania : String
          + ID : int
          + Ilosc : int
          + Kurier : String
          + oddzialKoncowy : String
          + oddzialPoczatkowy : String
          {static} + stage : Stage
          + status : String
          + DodajZlecenie()
          + UsunZlecenie()
          + WyswietlZlecenie()
          + Zlecenie()
          + Zlecenie()
          + Zlecenie()
          + Zlecenie()
          + ZmienZlecenie()
          {static} + fillCourierTable()
          {static} + fillOrderTable()
          {static} + fill_table()
          {static} + filltableCourier()
          {static} + filltableCurrentOrder()
          + getAdresKoncowy()
          + getAdresPoczatkowy()
          + getDataNadania()
          + getID()
          + getIlosc()
          + getKurier()
          + getOddzialKoncowy()
          + getOddzialPoczatkowy()
          + getStatus()
          + setAdresKoncowy()
          + setAdresPoczatkowy()
          + setDataNadania()
          + setID()
          + setIlosc()
          + setKurier()
          + setOddzialKoncowy()
          + setOddzialPoczatkowy()
          + setStatus()
      }
    }
  }
  

  project.Class.Cennik -up-|> project.Utils.DataUtil
  project.Class.Doplata -up-|> project.Utils.DataUtil
  project.Class.Klient -up-|> project.Class.Uzytkownik
  project.Class.Kurier -up-|> project.Class.Uzytkownik
  project.Class.Kurier o-- project.Class.TypKuriera : TypKuriera
  project.Class.Oddzial -up-|> project.Utils.DataUtil
  project.Class.Oplata -up-|> project.Utils.DataUtil
  project.Class.Oplata o-- project.Class.SposobPlatnosci : SposobPlatnosci
  project.Class.Paczka -up-|> project.Utils.DataUtil
  project.Class.Spedytor -up-|> project.Class.Uzytkownik
  project.Class.Uzytkownik -up-|> project.Utils.DataUtil
  project.Class.Zlecenie -up-|> project.Utils.DataUtil


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
