Drop Table ZlecenieKurier
Drop Table Kurier
Drop Table PaczkaDoplata
Drop Table Doplata
Drop Table Paczka
Drop Table Zlecenie
Drop Table Cennik
Drop Table Oplata
Drop Table Oddzial
Drop Table Adres
Drop Table Uzytkownik
Drop Table WyplataKurier