insert into Adres(ulica,nrDomu,miejscowosc,kodPocztowy) values ('Wschodnia','20','Kielce','25-004');
insert into Adres(ulica,nrDomu,miejscowosc,kodPocztowy) values ('Targowa','51','Warszawa','00-001');
insert into Adres(ulica,nrDomu,miejscowosc,kodPocztowy) values ('Warszawska','167','Kraków','30-002');
insert into Uzytkownik(imie, nazwisko,mail,haslo,telefon,typUzytkownika,adresId) values('Piotr','Walasek','piotr.walasek@gmail.com','klient','123456789','Klient','1');
insert into Uzytkownik(imie, nazwisko,mail,haslo,telefon,typUzytkownika,adresId) values('Dominik','Tuora','dominik.tuora@gmail.com','spedytor','189419848','Spedytor','2');
insert into Uzytkownik(imie, nazwisko,mail,haslo,telefon,typUzytkownika,adresId) values('Kamil','Mróz','mroz.kamil@gmail.com','kurier','123469532','Kurier','3');
insert into Oddzial(miejscowosc) values('Warszawa');
insert into Oddzial(miejscowosc) values('Kielce');
insert into Oddzial(miejscowosc) values('Kraków');
insert into Oplata(termin,kwota,status,sposob) values('20201217','10','Oplacone','Przelew');
insert into Oplata(termin,kwota,status,sposob) values('20201229','15','Nieoplacone','Przelew');
insert into Oplata(termin,kwota,status,sposob) values('20201221','20','Oplacone','Przelew');
insert into Cennik(gabaryt,kwota,opis,dataZmiany,limit) values('A','10','80x60x40','20200101','10');
insert into Cennik(gabaryt,kwota,opis,dataZmiany,limit) values('B','15','80x80x40','20200101','15');
insert into Cennik(gabaryt,kwota,opis,dataZmiany,limit) values('C','20','80x80x60','20200101','20');
insert into Zlecenie(dataNadania,adresPoczatkowy,adresKoncowy,status,uzytkownikId,oddzialPoczatkowyId,oddzialKoncowyID) values('20200110','Warszawa','aleja Tysi¹clecia Pañstwa Polskiego 7, 25-314 Kielce','Dostarczone','1','1','3');
insert into Zlecenie(dataNadania,adresPoczatkowy,adresKoncowy,status,uzytkownikId, oddzialPoczatkowyId,oddzialKoncowyID) values('20200111','Gdynia','Poznañ','Odebrane','1','3','2');
insert into Zlecenie(dataNadania,adresPoczatkowy,adresKoncowy,status,uzytkownikId,oddzialPoczatkowyId, oddzialKoncowyID) values('20200112','Katowice','Gdynia','Odebrane','1','2','1');
insert into Zlecenie(dataNadania,adresPoczatkowy,adresKoncowy,status,uzytkownikId,oddzialPoczatkowyId, oddzialKoncowyID) values('20200117','Kielce','Gdynia','Odebrane','1','2','1');
insert into Zlecenie(dataNadania,adresPoczatkowy,adresKoncowy,status,uzytkownikId,oddzialPoczatkowyId, oddzialKoncowyID) values('20200118','Skarzysko','Gdynia','Odebrane','1','2','1');
insert into Zlecenie(dataNadania,adresPoczatkowy,adresKoncowy,status,uzytkownikId,oddzialPoczatkowyId, oddzialKoncowyID) values('20200119','Tarnów','Katowice','Nowe','1','3','2');
insert into Paczka(waga,zlecenieId,cennikId,oplataId) values('5','1','1','1');
insert into Paczka(waga,zlecenieId,cennikId,oplataId) values('7','2','2','3');
insert into Paczka(waga,zlecenieId,cennikId,oplataId) values('8','3','3','2');
insert into Doplata(typDoplaty,kwota,dataZmiany) values('Przekroczenie rozmiaru','12','20200101');
insert into Doplata(typDoplaty,kwota,dataZmiany) values('Przekroczenie wagi','10','20200101');
insert into Doplata(typDoplaty,kwota,dataZmiany) values('Przesylka ekspresowa','5','20200101');
insert into PaczkaDoplata(paczkaId,doplataId) values('1','3');
insert into PaczkaDoplata(paczkaId,doplataId) values('2','2');
insert into Kurier(typKuriera,imie,nazwisko,uzytkownikId) values('Pocz¹tkowy','Kamil','Mróz','3');
insert into ZlecenieKurier(zlecenieId,kurierId,numerPorzadkowy) values('1','1','1');
insert into ZlecenieKurier(zlecenieId,kurierId,numerPorzadkowy) values('2','1','1');
insert into ZlecenieKurier(zlecenieId,kurierId,numerPorzadkowy) values('3','1','1');
insert into ZlecenieKurier(zlecenieId,kurierId,numerPorzadkowy) values('4','1','1');
